version: '3.6'

services:
  runner:
    image: highday/runner-image:v1.0
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUNNER_VERSION=2.313.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - REPO=highday-app/highday
      - ACCESS_TOKEN=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
    secrets:
      - personal_token
      - repo_name
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.70'
          memory: 4000M
        reservations:
          cpus: '0.50'
          memory: 3000M

secrets:
  personal_token:
    file: personal_token.txt
  repo_name:
    file: repo_name.txt
